# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      # On modifie la ligne principale pour ajouter ":cached" (meilleure perf sur Mac/Windows)
      - ./:/app:cached
      # On garde les volumes de configuration qui ne changent pas
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      
      # LIGNES AJOUTÉES : On utilise des volumes nommés pour le cache et les logs
      # Le contenu de /app/var/cache et /app/var/log sera maintenant dans des volumes Docker rapides
      - cache:/app/var/cache
      - log:/app/var/log
      
      # La ligne ci-dessous devient moins nécessaire avec la technique des volumes nommés,
      # qui est plus efficace, mais vous pouvez la laisser commentée.
      # - /app/vendor
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      database:
        condition: service_healthy

# LIGNES AJOUTÉES : Déclaration des volumes nommés à la racine du fichier
volumes:
  cache:
  log: